name: orchestrator-demo
region: syd1

services:
  # FastAPI Backend
  - name: backend
    github:
      repo: bikramkgupta/do-sandbox-demo
      branch: main
      deploy_on_push: false
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-d-2vcpu-4gb
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: DIGITALOCEAN_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: ${DIGITALOCEAN_TOKEN}
      - key: SPACES_BUCKET
        scope: RUN_TIME
        type: SECRET
        value: ${SPACES_BUCKET}
      - key: SPACES_REGION
        scope: RUN_TIME
        type: SECRET
        value: ${SPACES_REGION}
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SPACES_ACCESS_KEY}
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SPACES_SECRET_KEY}
      # Rate limiting - orchestrator guardrails
      - key: MAX_CONCURRENT_COLD
        scope: RUN_TIME
        value: "3"
      - key: MAX_CONCURRENT_WARM
        scope: RUN_TIME
        value: "3"
      - key: MAX_TOTAL_ACTIVE
        scope: RUN_TIME
        value: "10"
      - key: MAX_RUNS_PER_HOUR
        scope: RUN_TIME
        value: "25"
      # Warm pool settings - requires do-app-sandbox>=0.2.1
      - key: WARM_POOL_ENABLED
        scope: RUN_TIME
        value: "true"
      - key: WARM_POOL_TARGET_READY
        scope: RUN_TIME
        value: "3"
      - key: WARM_POOL_MAX_READY
        scope: RUN_TIME
        value: "5"
      - key: WARM_POOL_IDLE_TIMEOUT
        scope: RUN_TIME
        value: "600"
      - key: WARM_POOL_MAX_CONCURRENT_CREATES
        scope: RUN_TIME
        value: "1"
      # Sandbox lifetime settings
      - key: SANDBOX_MIN_LIFETIME_MINUTES
        scope: RUN_TIME
        value: "5"
      - key: SANDBOX_MAX_LIFETIME_MINUTES
        scope: RUN_TIME
        value: "10"

  # Next.js Frontend
  - name: frontend
    github:
      repo: bikramkgupta/do-sandbox-demo
      branch: main
      deploy_on_push: false
    source_dir: frontend
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-d-2vcpu-4gb
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: ""
      - key: BACKEND_URL
        scope: RUN_TIME
        value: ${backend.PRIVATE_URL}

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
