spec:
  name: sandbox-demo
  region: nyc

  services:
    # Next.js Frontend
    - name: frontend
      github:
        repo: YOUR_GITHUB_USERNAME/sandbox-demo
        branch: main
        deploy_on_push: true
      source_dir: frontend
      build_command: npm run build
      run_command: npm start
      http_port: 3000
      instance_count: 1
      instance_size_slug: apps-s-1vcpu-1gb
      routes:
        - path: /
      envs:
        - key: NEXT_PUBLIC_API_URL
          scope: RUN_TIME
          value: ${_self.PRIVATE_URL}
        - key: BACKEND_URL
          scope: RUN_TIME
          value: ${backend.PRIVATE_URL}

    # FastAPI Backend
    - name: backend
      github:
        repo: YOUR_GITHUB_USERNAME/sandbox-demo
        branch: main
        deploy_on_push: true
      source_dir: backend
      dockerfile_path: backend/Dockerfile
      http_port: 8000
      instance_count: 1
      instance_size_slug: apps-s-1vcpu-1gb
      routes:
        - path: /api
      envs:
        - key: DATABASE_URL
          scope: RUN_TIME
          value: ${db.DATABASE_URL}
        - key: DIGITALOCEAN_TOKEN
          scope: RUN_TIME
          type: SECRET
        - key: SPACES_BUCKET
          scope: RUN_TIME
          type: SECRET
        - key: SPACES_REGION
          scope: RUN_TIME
          type: SECRET
        - key: SPACES_ACCESS_KEY
          scope: RUN_TIME
          type: SECRET
        - key: SPACES_SECRET_KEY
          scope: RUN_TIME
          type: SECRET
        - key: MAX_CONCURRENT_COLD
          scope: RUN_TIME
          value: "2"
        - key: MAX_CONCURRENT_WARM
          scope: RUN_TIME
          value: "2"
        - key: MAX_TOTAL_ACTIVE
          scope: RUN_TIME
          value: "6"
        - key: MAX_RUNS_PER_HOUR
          scope: RUN_TIME
          value: "10"

  databases:
    - name: db
      engine: PG
      version: "16"
      size: db-s-dev-database
      num_nodes: 1
